# enable proxy to allow sharing of web views with other people
# this will make all your web views available at https://fftk.site/{your id}/{script name}/
enable_proxy: false

# port to run web server on for web views, most users should not need to change this
web_port: 31594

# port to transmit data on from ACT to the FFTK daemon, most users should not need to change this
port_data: 31593